### ISSUE TITLE
JSX desugar example wrong

### ISSUE THREAD

**Issue by saschatimme** [jaredly/jaredly.github.io#11]
Currently you write
```reason
<TodoApp some="thing" other=12>child1 child2</TodoApp>
/* becomes */
TodoApp.make some::"thing" other::12 [|child1, child2|];
```
but it actually becomes
```reason
ReasonReact.element (TodoApp.make some::"thing" other::12 [|child1, child2|]);
```

**Comment by naartjie** [comment]
Thanks @saschatimme, how could I get to this myself? Is there a set of commands you used?

**Comment by saschatimme** [comment]
It’s in the [reason react docs](https://reasonml.github.io/reason-react/#reason-react-jsx-capitalized) @naartjie

**Comment by naartjie** [comment]
Thanks @saschatimme. I thought you were grabbing it somewhere out of the compiled project files.

**Comment by jaredly** [comment]
added `(approximately)` :D
