### ISSUE TITLE
Link to record is incorrect

### ISSUE THREAD

**Issue by naartjie** [jaredly/jaredly.github.io#13]
Hi @jaredly, thanks so much for the `a-reason-react-tutorial`!

The link to `record` is broken, it is still pointing to the old site [`http://facebook.github.io/reason/#built-in-data-types-record`](http://facebook.github.io/reason/#built-in-data-types-record).

In the new site it is here [`https://reasonml.github.io/guide/language/record`](https://reasonml.github.io/guide/language/record).

I tried to do a PR, but for the life of me I can't figure out where that lives, it's like magic to me 😝

**Comment by jaredly** [comment]
fixed, thanks!
