### ISSUE TITLE
A ReasonReact Tutorial: minor fixes

### ISSUE THREAD

**Issue by voila** [jaredly/jaredly.github.io#7]
**In `Defining a component`**

https://github.com/reasonml/reason-react/blob/master/src/reasonReact.rei#L78 should be
https://github.com/reasonml/reason-react/blob/master/src/reasonReact.rei#L84

**In `Step 2 Rendering Items`**

_In OCaml,_ named arguments can be given in any order, but unnamed arguments cannot. So if you had a function let myfn = fun ::a ::b c d => {} where c was an int and d was a string, you could call it myfn b::2 a::1 3 "hi" or myfn a::3 3 "hi" b::1 but not myfn a::2 b::3 "hi" 4.

should it be:

_In Reason,_ named arguments can be given in any order, but unnamed arguments cannot. So if you had a function let myfn = fun ::a ::b c d => {} where c was an int and d was a string, you could call it myfn b::2 a::1 3 "hi" or myfn a::3 3 "hi" b::1 but not myfn a::2 b::3 "hi" 4.

As to avoid confusion between OCaml and Reason syntax ?

**Right after that, in `Rendering a list`**

`React.arrayToElement` should be `ReasonReact.arrayToElement`

**Comment by jaredly** [comment]
Thanks!
