### ISSUE TITLE
Expand /* ... */ in the upper part of TodoApp_1_3.re

### ISSUE THREAD

**Issue by fikriauliya** [jaredly/jaredly.github.io#9]
First of all, thx for the tutorial!

![screen shot 2017-07-09 at 9 52 32 pm](https://user-images.githubusercontent.com/341555/27994946-0b3461f2-64f1-11e7-8ab2-9d421de1e065.png)

I was a little bit confused on step 1_3 because of the `unbounded update error`. Based on the screen shot above, the only expected diffs from step 1_2 are those 10 lines. But in fact, there is a change on `render` fun parameter as well:

from `fun {state: {items}}` to `fun {state: {items}, update}`

It would be clearer if the snippet for 1_3 is to be expanded up, at least up to the `render` method signature.

**Comment by gandulio** [comment]
Ran into this too, I was convinced it was a bug until I took a look at the reason-react todomvc example and realized update needs to be specified as a parameter haha. 

And yes thanks so much for putting this together, this tutorial and the others you've put up have been helping me a lot!

**Comment by bado22** [comment]
I ran into the same thing but was trying to figure out how to fix it. Thanks for posting the solution here @fikriauliya & @gandulio!

**Comment by jaredly** [comment]
fixed, finally 😅
